experimental_approach={
  "func": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
  "dwi": [
    "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
    "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuralConnectivity",
    "@id: https://openminds.ebrains.eu/instances/experimentalApproach/anatomy"
  ],
  "fmap": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
  "anat": [
    "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
    "@id: https://openminds.ebrains.eu/instances/experimentalApproach/anatomy"
  ],
  "perf": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
  "meg": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
  "eeg": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/electrophysiology",
  "ieeg": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/electrophysiology",
  "beh": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/behavior",
  "pet": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/radiology",
  "micr": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/microscopy",
  "nirs": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging"
}

techniques={
  "angio": "Angiogram",
  "M0map": "Equilibrium magnetization (M0) map",
  "FLASH": "Fast-Low-Angle-Shot image",
  "FLAIR": "Fluid attenuated inversion recovery image",
  "UNIT1": "Homogeneous (flat) T1-weighted MP2RAGE image",
  "inplaneT1": "Inplane T1",
  "inplaneT2": "Inplane T2",
  "R1map": "Longitudinal relaxation rate image",
  "T1map": "Longitudinal relaxation time image",
  "MTVmap": "Macromolecular tissue volume (MTV) image",
  "MTRmap": "Magnetization transfer ratio image",
  "MTsat": "Magnetization transfer saturation image",
  "MWFmap": "Myelin water fraction image",
  "S0map": "Observed signal amplitude (S0) image",
  "R2starmap": "Observed transverse relaxation rate image",
  "T2starmap": "Observed transverse relaxation time image",
  "PDT2": "PD and T2 weighted image",
  "PDw": "Proton density (PD) weighted image",
  "PD": "Proton density image",
  "PDmap": "Proton density image",
  "Chimap": "Quantitative susceptibility map (QSM)",
  "RB1map": "RF receive sensitivity map",
  "TB1map": "RF transmit field image",
  "T1rho": "T1 in rotating frame (T1 rho) image",
  "T1w": "T1-weighted image",
  "T2w": "T2-weighted image",
  "T2star": "T2* image",
  "T2starw": "T2star weighted image",
  "R2map": "True transverse relaxation rate image",
  "T2map": "True transverse relaxation time image",
  "bold": "Blood-Oxygen-Level Dependent image",
  "cbv": "Cerebral blood volume image",
  "phase": "Phase image",
  "defacemask": "Defacing masks",
  "epi": "EPI",
  "fieldmap": "Fieldmap",
  "magnitude": "Magnitude",
  "magnitude1": "Magnitude",
  "magnitude2": "Magnitude",
  "phase1": "Phase",
  "phase2": "Phase",
  "phasediff": "Phase-difference",
  "dwi": "@id: https://openminds.ebrains.eu/instances/technique/diffusionWeightedImaging",
  "sbref": "Single-band reference image",
  "asl": "Arterial Spin Labeling",
  "m0scan": "M0",
  "eeg": "@id:https://openminds.ebrains.eu/instances/technique/electroencephalography",
  "ieeg": "Intracranial Electroencephalography",
  "physio": "Physiological continuous recordings",
  "stim": "stimulation continuous recordings",
  "beh": "Behavioral experiments",
  "pet": "@id:https://openminds.ebrains.eu/instances/technique/positronEmissionTomography",
  "2PE": "2-photon excitation microscopy",
  "BF": "Bright-field microscopy",
  "CARS": "Coherent anti-Stokes Raman spectroscopy",
  "CONF": "Confocal microscopy",
  "DIC": "Differential interference contrast microscopy",
  "DF": "Dark-field microscopy",
  "FLUO": "Fluorescence microscopy",
  "MPE": "Multi-photon excitation microscopy",
  "NLO": "Nonlinear optical microscopy",
  "OCT": "Optical coherence tomography",
  "PC": "Phase-contrast microscopy",
  "PLI": "Polarized-light microscopy",
  "SEM": "Scanning electron microscopy",
  "SPIM": "Selective plane illumination microscopy",
  "SR": "Super-resolution microscopy",
  "TEM": "Transmission electron microscopy",
  "uCT": "Micro-CT",
  "nirs": "Near-Infrared Spectroscopy ",
  "motion": "Motion"
}